name: appodeal_flutter
description: A Flutter plugin to display ads from Appodeal; it supports the new reqs for iOS 14+ and GDPR/CCPA consent.
version: 0.3.0
homepage: https://github.com/vegidio-flutter/appodeal

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.vinicius.appodeal_flutter
        pluginClass: AppodealFlutterPlugin
      ios:
        pluginClass: AppodealFlutterPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"